# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Programok\cmake\bin\cmake.exe

# The command to remove a file.
RM = D:\Programok\cmake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\Alonso\Documents\Visual Studio Code\Ballbreaker3D2016"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\Alonso\Documents\Visual Studio Code\Ballbreaker3D2016"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\Programok\cmake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\Programok\cmake\bin\cmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Alonso\Documents\Visual Studio Code\Ballbreaker3D2016\CMakeFiles" "D:\Alonso\Documents\Visual Studio Code\Ballbreaker3D2016\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Alonso\Documents\Visual Studio Code\Ballbreaker3D2016\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Platinum_demo

# Build rule for target.
Platinum_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Platinum_demo
.PHONY : Platinum_demo

# fast build rule for target.
Platinum_demo/fast:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/build
.PHONY : Platinum_demo/fast

Application.obj: Application.cpp.obj

.PHONY : Application.obj

# target to build an object file
Application.cpp.obj:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Application.cpp.obj
.PHONY : Application.cpp.obj

Application.i: Application.cpp.i

.PHONY : Application.i

# target to preprocess a source file
Application.cpp.i:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Application.cpp.i
.PHONY : Application.cpp.i

Application.s: Application.cpp.s

.PHONY : Application.s

# target to generate assembly for a file
Application.cpp.s:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Application.cpp.s
.PHONY : Application.cpp.s

Game.obj: Game.cpp.obj

.PHONY : Game.obj

# target to build an object file
Game.cpp.obj:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Game.cpp.obj
.PHONY : Game.cpp.obj

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Game.cpp.s
.PHONY : Game.cpp.s

Menu.obj: Menu.cpp.obj

.PHONY : Menu.obj

# target to build an object file
Menu.cpp.obj:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Menu.cpp.obj
.PHONY : Menu.cpp.obj

Menu.i: Menu.cpp.i

.PHONY : Menu.i

# target to preprocess a source file
Menu.cpp.i:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Menu.cpp.i
.PHONY : Menu.cpp.i

Menu.s: Menu.cpp.s

.PHONY : Menu.s

# target to generate assembly for a file
Menu.cpp.s:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Menu.cpp.s
.PHONY : Menu.cpp.s

Object.obj: Object.cpp.obj

.PHONY : Object.obj

# target to build an object file
Object.cpp.obj:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Object.cpp.obj
.PHONY : Object.cpp.obj

Object.i: Object.cpp.i

.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s

.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Object.cpp.s
.PHONY : Object.cpp.s

Sound.obj: Sound.cpp.obj

.PHONY : Sound.obj

# target to build an object file
Sound.cpp.obj:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Sound.cpp.obj
.PHONY : Sound.cpp.obj

Sound.i: Sound.cpp.i

.PHONY : Sound.i

# target to preprocess a source file
Sound.cpp.i:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Sound.cpp.i
.PHONY : Sound.cpp.i

Sound.s: Sound.cpp.s

.PHONY : Sound.s

# target to generate assembly for a file
Sound.cpp.s:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/Sound.cpp.s
.PHONY : Sound.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\Platinum_demo.dir\build.make CMakeFiles/Platinum_demo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Platinum_demo
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Application.obj
	@echo ... Application.i
	@echo ... Application.s
	@echo ... Game.obj
	@echo ... Game.i
	@echo ... Game.s
	@echo ... Menu.obj
	@echo ... Menu.i
	@echo ... Menu.s
	@echo ... Object.obj
	@echo ... Object.i
	@echo ... Object.s
	@echo ... Sound.obj
	@echo ... Sound.i
	@echo ... Sound.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

